version: "3.8"
services:

  project-name_back:
    build: ./
    container_name: project-name_back
    networks:
      - project-name
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

networks:
  project-name:
    driver: bridge         
    ipam:
      config:
        - subnet: 172.32.0.0/16